checks:
  method-complexity:
    config:
      threshold: 7
  method-lines:
    config:
      threshold: 30
  method-count:
    config:
      threshold: 25

plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
  nodesecurity:
    enabled: true
  git-legal:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - TODO
  shellcheck:
    enabled: true

ratings:
  paths:
    - "packages/*/src/**/*.js"
    - "packages/*/*.js"
exclude_paths:
  - "packages/uuid/benchmark/"
  - "packages/*/tests/"
  - "build/"
